# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8405ffbf-d6f8-4e81-9095-4b7f00d6cc2e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8405ffbf-d6f8-4e81-9095-4b7f00d6cc2e".device = "/dev/disk/by-uuid/8405ffbf-d6f8-4e81-9095-4b7f00d6cc2e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BC69-A081";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
