# Copied from https://github.com/kclejeune/system/blob/master/.github/workflows/build.yml. Modified.
name: 'system build'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # IFD is broken on darwin? https://github.com/NixOS/nix/pull/6988
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
